# fly.toml file generated for bling-dashboard on 2022-12-03T17:06:31-03:00

app = "bling-dashboard"
primary_region = "gru"
kill_timeout = 15
swap_size_mb = 512

[http_service]
http_checks = []
force_https = true
internal_port = 3000
auto_start_machines = true
auto_stop_machines = "suspend"
min_machines_running = 0
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[http_service.checks]]
grace_period = "5s"
interval = "15s"
method = "GET"
path = "/api/health"
restart_limit = 0
timeout = "5s"
